version: "3.5"
services:
  timeline-db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_persistence:/var/lib/postgresql/data
  timeline-backend:
    build: backend
    environment:
      - BACKEND_DEBUG
      - BACKEND_SECRET_KEY
    depends_on:
      - timeline-db
    volumes:
      - ./backend/source:/usr/src/app
      - archives:/data/archives
      - backups:/data/backups
      - previews:/data/previews
      - backend_staticfiles:/assets/static
      - ./scripts:/usr/src/scripts:ro
      - ssh_keys:/root/.ssh
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  timeline-frontend:
    image: nginx
    volumes:
      - ./frontend/source:/usr/share/nginx/html:ro
    depends_on:
      - timeline-backend
    logging:
      driver: "none"
  mqtt-broker:
    build: mqtt-broker
    environment:
      - MQTT_USERNAME
      - MQTT_PASSWORD
    volumes:
      - mqtt_persistence:/mosquitto/data
    ports:
      - 1883:1883
  geolocation-client:
    build: geolocation-client
    environment:
      - MQTT_USERNAME
      - MQTT_PASSWORD
    depends_on:
      - mqtt-broker
      - timeline-backend
    volumes:
      - ./geolocation-client/source:/usr/src/app
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  proxy:
    build: proxy
    depends_on:
      - timeline-frontend
      - timeline-backend
    volumes:
      - archives:/data/archives
      - backups:/data/backups
      - previews:/assets/previews
      - backend_staticfiles:/assets/static
    logging:
      options:
        max-size: "200k"
        max-file: "10"
volumes:
  db_persistence:
  mqtt_persistence:
  backups:
  archives:
  previews:
  ssh_keys:
  backend_staticfiles:
