version: "3.5"
services:
  timeline-backend:
    volumes:
      - /var/foldersync/photos:/data/mounts/photos
      - /var/foldersync/screenshots:/data/mounts/screenshots
      - /var/foldersync/telegram:/data/mounts/telegram
  proxy:
    volumes:
      - /var/foldersync/photos:/data/mounts/photos
      - /var/foldersync/screenshots:/data/mounts/screenshots
      - /var/foldersync/telegram:/data/mounts/telegram
    networks:
      default:
      homeserver:
         aliases:
            - timeline
networks:
  homeserver:
    external:
      name: homeserver
