version: "2.1"
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_persistence:/var/lib/postgresql/data
    userns_mode: "host"
  backend:
    build: backend
    environment:
      - BACKEND_DEBUG
      - BACKEND_SECRET_KEY
    depends_on:
      - db
    volumes:
      - ./backend/source:/usr/src/app
      - backups:/srv/backups
      - previews:/srv/previews
      - backend_staticfiles:/srv/static
      - ./scripts:/usr/src/scripts:ro
      - ssh_keys:/root/.ssh
    privileged: true
    userns_mode: "host"
  frontend:
    image: nginx
    volumes:
      - ./frontend/source:/usr/share/nginx/html:ro
    depends_on:
      - backend
  proxy:
    build: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - backups:/srv/backups
      - previews:/srv/previews
      - backend_staticfiles:/srv/static
      - "./proxy/ssl-certs:/etc/ssl/certs"
volumes:
  db_persistence:
  backups:
  previews:
  ssh_keys:
  backend_staticfiles: