# Generated by Django 3.1.2 on 2021-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0016_auto_20210502_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraktSource',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('consumer_key', models.CharField(max_length=100)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100)),
                ('access_token_created', models.IntegerField(null=True)),
                ('access_token_expires_in', models.IntegerField(null=True)),
                ('client_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
